openapi: 3.0.3
info:
  title: Campaign Products Import API
  version: '1.0.0'

paths:
  /api/v1/campaigns/{campaign_id}/products/import:
    post:
      tags: [Campaigns]
      summary: Upload Excel to import products/plans/commissions for a campaign
      operationId: campaignProductsImportCreate
      parameters:
        - in: path
          name: campaign_id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file: { contentType: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet }
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignProductsImportAccepted'
              examples:
                accepted:
                  value: { task_id: CPI20251015001, status: accepted }

  /api/v1/campaigns/{campaign_id}/products/import/{task_id}:
    get:
      tags: [Campaigns]
      summary: Get products import task status/result
      operationId: campaignProductsImportStatus
      parameters:
        - in: path
          name: campaign_id
          required: true
          schema: { type: string }
        - in: path
          name: task_id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignProductsImportStatus'
              examples:
                done:
                  value:
                    task_id: CPI20251015001
                    status: succeeded
                    total_rows: 120
                    succeeded: 118
                    failed: 2
                    result_url: https://mock/campaigns/C1/import/CPI20251015001/result.csv

components:
  schemas:
    CampaignProductsImportAccepted:
      type: object
      properties:
        task_id: { type: string }
        status: { type: string, enum: [accepted] }
      required: [task_id, status]

    CampaignProductsImportStatus:
      type: object
      properties:
        task_id: { type: string }
        status: { type: string, enum: [accepted, processing, succeeded, failed] }
        total_rows: { type: integer }
        succeeded: { type: integer }
        failed: { type: integer }
        result_url: { type: string }
      required: [task_id, status]
