openapi: 3.0.3
info:
  title: Commission Copy From API
  version: '1.0.0'

paths:
  /api/v1/commission/copy_from:
    post:
      tags: [Commission]
      summary: Copy commission rules from a source (campaign/team/template) to current scope
      operationId: commissionCopyFrom
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommissionCopyFromRequest'
            examples:
              from_campaign:
                value:
                  target: { campaign_id: C1, plan_id: P1, team_id: T001 }
                  source: { type: campaign, campaign_id: C0, plan_id: P9 }
                  preview: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommissionCopyFromResult'
              examples:
                preview:
                  value:
                    preview: true
                    diff:
                      added: 120
                      changed: 45
                      unchanged: 300
                applied:
                  value:
                    preview: false
                    applied: 165

components:
  schemas:
    CommissionCopyFromRequest:
      type: object
      properties:
        target:
          type: object
          properties:
            campaign_id: { type: string }
            plan_id: { type: string }
            team_id: { type: string }
          required: [campaign_id, plan_id]
        source:
          type: object
          properties:
            type:
              type: string
              enum: [campaign, team, template]
            campaign_id: { type: string }
            plan_id: { type: string }
            team_id: { type: string }
            template_id: { type: string }
          required: [type]
        preview: { type: boolean, default: true }
      required: [target, source]

    CommissionCopyFromResult:
      type: object
      properties:
        preview: { type: boolean }
        applied: { type: integer }
        diff:
          type: object
          properties:
            added: { type: integer }
            changed: { type: integer }
            unchanged: { type: integer }
